name: "Release Dev"

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/reusable_setup.yml
    secrets:
      JIG_GH_RELEASE_TOKEN: ${{ secrets.JIG_GH_RELEASE_TOKEN }}

  lint-test:
    needs: 'setup'
    uses: ./.github/workflows/reusable_lint-packages.yml
    secrets:
      JIG_GH_RELEASE_TOKEN: ${{ secrets.JIG_GH_RELEASE_TOKEN }}

  build-packages:
    needs: 'setup'
    uses: ./.github/workflows/reusable_build-packages.yml
    secrets:
      JIG_GH_RELEASE_TOKEN: ${{ secrets.JIG_GH_RELEASE_TOKEN }}

  unit-tests:
    needs: 'setup'
    uses: ./.github/workflows/reusable_unit-tests.yml
    secrets:
      JIG_GH_RELEASE_TOKEN: ${{ secrets.JIG_GH_RELEASE_TOKEN }}

  release-npm-dev:
    needs: ['build-packages', 'lint-test', 'unit-tests']
    uses: ./.github/workflows/reusable_release-npm.yml
    with:
      create-dev-release: true
      create-rc-release: false
    secrets:
      JIG_GH_RELEASE_TOKEN: ${{ secrets.JIG_GH_RELEASE_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
